## ***Intro***

Sometimes, more complex models can provide better performance on challenging tasks. After trying simpler models, it can be beneficial to explore more sophisticated approaches.

Artificial Neural Networks, inspired by the structure and function of the human brain, are powerful models capable of capturing intricate patterns in data. For binary classification tasks, neural networks can be particularly effective. They consist of layers of interconnected neurons, where each neuron applies a transformation to its input and passes the result to the next layer. Roughly, neuron acts like a logistic regression model with different "activation functions", they are often reffered to as **perceptrons**.

In this notebook, we address a binary classification problem (**predicting loan defaults**) using a neural network. Our model consists of an input layer, one hidden layer with 100 neurons, and an output layer with a single neuron using the sigmoid activation function (like in logistic regression) to produce a probability score.

## ***Imports***

In [1]:
# For data manipulation and linear algebra
import pandas as pd
import numpy as np

# To build a keras model
from keras import Sequential
from keras.layers import Dense, InputLayer, Normalization, Dropout
from keras.optimizers import Adam

# some utilities from Scikit learn and Imbalanced-learn
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight

2024-05-27 14:48:49.584423: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-27 14:48:49.584472: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-27 14:48:49.585924: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

## ***Functions***

In [2]:
def convert_to_tensor(*args, target=False) -> tuple:
    """Converts one or more DataFrames to Tensors.

    This function takes one or more DataFrames as input and returns a tuple of Tensors.

    Args:
    *args: A variable number of DataFrames to be converted.
    target: (Optional) Boolean flag indicating the data type of the output Tensors.
    - If True (default: False), Tensors will have the original data types of the DataFrame columns.
    - If False, Tensors will be cast to float type.

    Returns:
    A tuple of Tensors, one for each input DataFrame.
    """
    # Create a tensor from dataframe (convert inputs to float)
    return (np.array(df)for df in args) if target else (np.array(df).astype(float) for df in args)

## ***Data preparation***

**We will use a base table of 100 features selected from a set of features generated with Deep Feature Synthesis on the Home Credit - Credit Risk Model Stability competition dataset totaling over 1,500,000 examples.**

In [3]:
dataset = pd.read_parquet("/kaggle/input/base_100features.parquet")
dataset

,WEEK_NUM,COUNT(person_1),MODE(person_1.contaddr_district_15M),MODE(person_1.contaddr_zipcode_807M),MODE(person_1.education_927M),MODE(person_1.empladdr_district_926M),MODE(person_1.empladdr_zipcode_114M),MODE(person_1.incometype_1044T),MODE(person_1.language1_981M),MODE(person_1.role_1084L),...,MODE(static_cb_0.education_88M),MODE(static_cb_0.maritalst_385M),MODE(static_cb_0.requesttype_4525192L),SUM(static_cb_0.days120_123L),SUM(static_cb_0.days30_165L),MAX_MIN_DELTA(applprev_2.num_group2),MONTH(date_decision),SEASON(date_decision),WEEKDAY(date_decision),target
case_id,,,,,,,,,,,,,,,,,,,,,
0,0,4,259,2828,5,221,2093,6,2,2,...,2,2,0,0.0,0.0,0.0,1,3,3,0
1,0,5,259,2828,5,221,2093,6,2,0,...,2,2,0,0.0,0.0,0.0,1,3,3,0
2,0,5,259,2828,5,221,2093,8,2,0,...,2,2,0,0.0,0.0,1.0,1,3,4,0
3,0,3,259,2828,5,221,2093,8,2,0,...,2,2,0,0.0,0.0,2.0,1,3,3,0
4,0,4,259,2828,5,221,2093,8,2,2,...,2,2,0,0.0,0.0,1.0,1,3,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2703450,91,1,143,356,5,221,2093,0,1,0,...,4,3,0,0.0,0.0,2.0,10,0,0,0
2703451,91,2,403,2825,5,221,2093,0,1,0,...,4,3,0,0.0,0.0,3.0,10,0,0,0
2703452,91,1,273,3202,5,221,2093,1,1,0,...,4,3,0,2.0,0.0,1.0,10,0,0,0
2703453,91,2,148,1959,5,221,2093,0,1,0,...,4,0,0,2.0,1.0,3.0,10,0,0,0
2703454,91,1,42,251,5,221,2093,0,0,0,...,4,5,0,1.0,0.0,3.0,10,0,0,0

In [4]:
# You can notice that the positive class is extremely under represented (totalling about 3% of the entire dataset)
# This complicates the training process as the model will likely get a 97% classification accuracy by always prediction class 0
# So we have to find a solution to that problem first
dataset[dataset["target"] == 1]

,WEEK_NUM,COUNT(person_1),MODE(person_1.contaddr_district_15M),MODE(person_1.contaddr_zipcode_807M),MODE(person_1.education_927M),MODE(person_1.empladdr_district_926M),MODE(person_1.empladdr_zipcode_114M),MODE(person_1.incometype_1044T),MODE(person_1.language1_981M),MODE(person_1.role_1084L),...,MODE(static_cb_0.education_88M),MODE(static_cb_0.maritalst_385M),MODE(static_cb_0.requesttype_4525192L),SUM(static_cb_0.days120_123L),SUM(static_cb_0.days30_165L),MAX_MIN_DELTA(applprev_2.num_group2),MONTH(date_decision),SEASON(date_decision),WEEKDAY(date_decision),target
case_id,,,,,,,,,,,,,,,,,,,,,
4,0,4,259,2828,5,221,2093,8,2,2,...,2,2,0,0.0,0.0,1.0,1,3,4,1
101,0,4,259,2828,5,221,2093,1,2,2,...,2,2,0,0.0,0.0,1.0,1,3,3,1
118,0,4,259,2828,5,221,2093,1,2,2,...,2,2,0,0.0,0.0,0.0,1,3,3,1
129,0,4,259,2828,5,221,2093,8,2,2,...,2,2,0,0.0,0.0,0.0,1,3,4,1
148,0,4,259,2828,5,221,2093,1,2,2,...,2,2,0,0.0,0.0,0.0,1,3,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2702884,91,1,515,2177,5,221,2093,6,0,0,...,4,4,0,0.0,0.0,1.0,10,0,4,1
2702904,91,1,297,1304,5,221,2093,8,1,0,...,4,0,0,1.0,1.0,2.0,10,0,4,1
2703005,91,1,232,233,5,221,2093,6,0,0,...,4,0,0,3.0,3.0,2.0,10,0,5,1
2703400,91,1,798,1536,5,221,2093,8,1,0,...,4,0,0,8.0,4.0,2.0,10,0,0,1
2703411,91,1,511,1850,5,221,2093,6,1,0,...,4,0,0,2.0,0.0,5.0,10,0,0,1

In [5]:
# Drop WEEK_NUM and target to form the training entries X (you can use WEEK_NUM as a feature too))
week_num = dataset["WEEK_NUM"]
target = dataset["target"]
dataset.drop(columns=["WEEK_NUM", "target"], inplace=True)
dataset

,COUNT(person_1),MODE(person_1.contaddr_district_15M),MODE(person_1.contaddr_zipcode_807M),MODE(person_1.education_927M),MODE(person_1.empladdr_district_926M),MODE(person_1.empladdr_zipcode_114M),MODE(person_1.incometype_1044T),MODE(person_1.language1_981M),MODE(person_1.role_1084L),MODE(person_1.sex_738L),...,MODE(static_cb_0.education_1103M),MODE(static_cb_0.education_88M),MODE(static_cb_0.maritalst_385M),MODE(static_cb_0.requesttype_4525192L),SUM(static_cb_0.days120_123L),SUM(static_cb_0.days30_165L),MAX_MIN_DELTA(applprev_2.num_group2),MONTH(date_decision),SEASON(date_decision),WEEKDAY(date_decision)
case_id,,,,,,,,,,,,,,,,,,,,,
0,4,259,2828,5,221,2093,6,2,2,0,...,3,2,2,0,0.0,0.0,0.0,1,3,3
1,5,259,2828,5,221,2093,6,2,0,1,...,3,2,2,0,0.0,0.0,0.0,1,3,3
2,5,259,2828,5,221,2093,8,2,0,0,...,3,2,2,0,0.0,0.0,1.0,1,3,4
3,3,259,2828,5,221,2093,8,2,0,0,...,3,2,2,0,0.0,0.0,2.0,1,3,3
4,4,259,2828,5,221,2093,8,2,2,0,...,3,2,2,0,0.0,0.0,1.0,1,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2703450,1,143,356,5,221,2093,0,1,0,0,...,4,4,3,0,0.0,0.0,2.0,10,0,0
2703451,2,403,2825,5,221,2093,0,1,0,0,...,4,4,3,0,0.0,0.0,3.0,10,0,0
2703452,1,273,3202,5,221,2093,1,1,0,1,...,4,4,3,0,2.0,0.0,1.0,10,0,0
2703453,2,148,1959,5,221,2093,0,1,0,0,...,1,4,0,0,2.0,1.0,3.0,10,0,0
2703454,1,42,251,5,221,2093,0,0,0,0,...,4,4,5,0,1.0,0.0,3.0,10,0,0

In [6]:
# Split the dataset into training and test sets (randomly shuffling the data)
# Only 5% of the data will be used as the test set (the dataset being really big, 5% should be largely enough)
X_train, X_test, Y_train, Y_test = train_test_split(dataset, target, test_size=0.05, shuffle=True, random_state=123)

In [7]:
# keep the true test labels in a Dataframe before converting to tensor
true_label_test = pd.DataFrame(Y_test)
true_label_test

         target
case_id
1017805       0
2543910       0
225134        0
955887        0
23690         0
...         ...
2540270       0
2553269       0
947602        0
755641        0
1663420       0

[76333 rows x 1 columns]

In [8]:
# Convert Xs and Ys to tensor (np.ndarray)
X_train, X_test = convert_to_tensor(X_train, X_test)
Y_train, Y_test = convert_to_tensor(Y_train, Y_test, target=True)

In [9]:
X_train.shape, X_test.shape

((1450326, 100), (76333, 100))

In [10]:
Y_train.dtype, X_train.dtype

(dtype('int64'), dtype('float64'))

## ***Create a normalization layer***

**This layer will act as a preprocessing layer that shifts and scale inputs into a distribution centered around 0 with standard deviation 1. It accomplishes this by precomputing the mean and variance of the data, and calling (input - mean) / sqrt(var) at runtime.**

In [11]:
normalizer = Normalization()
normalizer.adapt(X_train)

In [12]:
normalizer(X_test[0])

<tf.Tensor: shape=(1, 100), dtype=float32, numpy=
array([[ 0.04624718, -0.28207028, -1.983003  , -4.6552796 ,  0.24187519,
         0.1974189 ,  0.78313464,  1.1939479 , -0.37999895, -0.7762619 ,
        -1.37151   , -0.24940884, -2.189564  ,  0.6568108 , -1.0199935 ,
        -0.9235781 , -1.0008069 ,  0.49003232, -1.182728  ,  0.6504714 ,
         0.521577  , -0.02339314, -0.68215513, -0.16142493, -0.9974977 ,
        -0.7085818 ,  0.12254757,  0.11174086, -0.6286927 ,  0.75663817,
        -0.5329664 , -1.0458726 , -0.71103936, -0.11861729, -0.02432021,
        -0.8803327 , -0.38889712, -2.001316  , -0.47380036, -1.3275441 ,
        -1.390471  , -1.5428802 , -0.87488216, -0.9901183 , -0.85514   ,
        -1.6092083 , -1.287082  , -1.0557376 , -0.81731623, -1.3617547 ,
        -0.79203176, -1.005219  , -0.14500466,  0.01480454,  0.42456862,
        -0.78026426, -0.5758279 ,  0.37803945, -0.7489058 , -0.6271946 ,
        -1.0284047 , -0.9170442 , -0.64738584, -0.5287307 , -0.40075794,
        -0.68189234, -0.66453195, -0.51602376, -0.34319526, -0.29621255,
        -0.61305314, -0.60624444,  0.5536208 , -0.6305141 , -0.09753338,
        -0.58637345, -0.3678717 , -0.07309855, -0.6250332 , -0.74385357,
        -0.8940848 ,  1.0469856 , -0.60115755, -0.07322425, -0.07697114,
        -0.2654873 , -0.454303  , -1.5782964 , -0.7748151 , -2.6455812 ,
         0.83277   ,  0.15779534,  0.5502312 , -0.80525017, -0.71587265,
        -0.5403103 , -1.3926358 ,  0.7326359 ,  0.31888232, -0.49515057]],
      dtype=float32)>

## ***Create and compile model***

In [13]:
optimizer = Adam(learning_rate=0.001)

In [14]:
# Whether training on tpu; this flag determines whether or not to apply some configurations to use Tensor Processing Unit on Kaggle
use_tpu = False

In [15]:
# Create a logistic regression model
if use_tpu:
    # detect and init the TPU
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver()

    # instantiate a distribution strategy
    tf.tpu.experimental.initialize_tpu_system(tpu)
    tpu_strategy = tf.distribute.TPUStrategy(tpu)

    # instantiating the model in the strategy scope creates the model on the TPU
    with tpu_strategy.scope():
        model = Sequential([InputLayer(shape=(100,)), normalizer,
                        Dense(units=100, activation="relu", kernel_initializer="glorot_uniform", kernel_regularizer="l2"),
                        Dense(units=1, activation="sigmoid", kernel_initializer="glorot_uniform", kernel_regularizer=None)], name="shallow_Neural_Net")
        # Compile the model for training
        model.compile(optimizer=optimizer, loss="binary_crossentropy", metrics=["accuracy", "auc", "precision", "recall"])

else:
    model = Sequential([InputLayer(shape=(100,)), normalizer,
                        Dense(units=100, activation="relu", kernel_initializer="glorot_uniform", kernel_regularizer="l2"),
                        Dense(units=1, activation="sigmoid", kernel_initializer="glorot_uniform", kernel_regularizer=None)], name="shallow_Neural_Net")
    # Compile the model for training
    model.compile(optimizer=optimizer, loss="binary_crossentropy", metrics=["accuracy", "auc", "precision", "recall"])

## ***Dealing with imbalance***

As we observed earlier, the dataset is highly unbalanced, requiring a strategy for the model to effectively learn to distinguish between the two classes. Without such a strategy, the model is likely to predict class 0 for almost every example and still achieve a high classification accuracy. Therefore, accuracy is not as relevant for this kind of dataset. To evaluate the model, we need metrics that can assess its ability to **recognize the minority class**. By weighting the classes, we penalize the model more heavily for misclassifying the minority class than the majority class.

Additionally, we will use precision and recall to evaluate the model's performance. Both metrics provide insights into the model's ability to accurately predict the positive class. Precision measures the percentage of true positive predictions among all examples predicted as positive, while recall measures the percentage of actual positive cases that the model correctly identified as positive.

In [16]:
# Compute class weight before calling model.fit
# Run if not dataset resampled (to train on the whole training set)
class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(Y_train), y=Y_train)
class_weights = {0: class_weights[0], 1: class_weights[1]}
class_weights

{0: 0.5162114467827323, 1: 15.921202274573517}

## ***Training***

In [17]:
# Train for 10 epochs
model.fit(x=X_train, y=Y_train, batch_size=64, class_weight=class_weights, epochs=10, shuffle=True)

Epoch 1/10
   86/22662 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.3898 - auc: 0.5014 - loss: 1.6364 - precision: 0.0293 - recall: 0.6414

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1716821405.142151    1429 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

22662/22662 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.6751 - auc: 0.7490 - loss: 0.6794 - precision: 0.0646 - recall: 0.6917
Epoch 2/10
22662/22662 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.6786 - auc: 0.7673 - loss: 0.5882 - precision: 0.0672 - recall: 0.7179
Epoch 3/10
22662/22662 ━━━━━━━━━━━━━━━━━━━━ 39s 2ms/step - accuracy: 0.6798 - auc: 0.7686 - loss: 0.5860 - precision: 0.0676 - recall: 0.7183
Epoch 4/10
22662/22662 ━━━━━━━━━━━━━━━━━━━━ 39s 2ms/step - accuracy: 0.6793 - auc: 0.7688 - loss: 0.5847 - precision: 0.0676 - recall: 0.7216
Epoch 5/10
22662/22662 ━━━━━━━━━━━━━━━━━━━━ 39s 2ms/step - accuracy: 0.6808 - auc: 0.7674 - loss: 0.5883 - precision: 0.0682 - recall: 0.7199
Epoch 6/10
22662/22662 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.6761 - auc: 0.7700 - loss: 0.5869 - precision: 0.0681 - recall: 0.7257
Epoch 7/10
22662/22662 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.6835 - auc: 0.7690 - loss: 0.5839 - precision: 0.0681 - recall: 0.7183
Epoch 8/10
22662/22662 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.6841 - auc: 0.7693 - loss: 0.5851 - precision: 0.0687 - recall: 0.7189
Epoch 9/10
22662/22662 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.6843 - auc: 0.7709 - loss: 0.5828 - precision: 0.0689 - recall: 0.7207
Epoch 10/10
22662/22662 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.6829 - auc: 0.7679 - loss: 0.5854 - precision: 0.0681 - recall: 0.7154

In [18]:
model.summary()

Model: "shallow_Neural_Net"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ normalization (Normalization)   │ (None, 100)            │           201 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 30,806 (120.34 KB)

 Trainable params: 10,201 (39.85 KB)

 Non-trainable params: 201 (808.00 B)

 Optimizer params: 20,404 (79.71 KB)

## ***Evaluation***

In [19]:
model.evaluate(x=X_test, y=Y_test)

2386/2386 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.6936 - auc: 0.7738 - loss: 0.5865 - precision: 0.0701 - recall: 0.7036

[0.5861420631408691,
 0.6932912468910217,
 0.7667088508605957,
 0.06970157474279404,
 0.6939108967781067]

In [20]:
y_pred_prob = model.predict(x=X_test)
y_pred_prob

2386/2386 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step

array([[0.11642805],
       [0.37935573],
       [0.11854824],
       ...,
       [0.41046274],
       [0.33519045],
       [0.2877821 ]], dtype=float32)

In [21]:
y_pred = np.where(y_pred_prob > 0.5, 1, 0)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [22]:
true_label_test["predicted probs"] = y_pred_prob
true_label_test["predicted class"] = y_pred
true_label_test

         target  predicted probs  predicted class
case_id
1017805       0         0.116428                0
2543910       0         0.379356                0
225134        0         0.118548                0
955887        0         0.235079                0
23690         0         0.392194                0
...         ...              ...              ...
2540270       0         0.432315                0
2553269       0         0.688489                1
947602        0         0.410463                0
755641        0         0.335190                0
1663420       0         0.287782                0

[76333 rows x 3 columns]

## ***Conclusion***

**Feel free to tune the hyper-parameters of the model or to train with a different set of features. Thanks for reading**