## ***Intro***

Ensemble methods often strike a balance between simplicity and performance, making them a go-to choice for many classification tasks.

Random forests are a robust ensemble learning method that combine the predictions of multiple decision trees to improve generalization and accuracy. By averaging the outputs of various trees, random forests mitigate the risk of overfitting that individual decision trees often face. This makes them particularly suitable for complex classification tasks.

In this notebook, we tackle a binary classification problem (**predicting loan defaults**) using a random forest.

## ***Imports***

In [1]:
# For data manipulation and linear algebra
import pandas as pd
import numpy as np

# some utilities from Scikit learn
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score, recall_score, roc_auc_score, accuracy_score
from sklearn.pipeline import make_pipeline

# The Random Forest classifier
from sklearn.ensemble import RandomForestClassifier

## ***Functions***

In [2]:
def convert_to_tensor(*args, target=False) -> tuple:
    """Converts one or more DataFrames to Tensors.

    This function takes one or more DataFrames as input and returns a tuple of Tensors.

    Args:
    *args: A variable number of DataFrames to be converted.
    target: (Optional) Boolean flag indicating the data type of the output Tensors.
    - If True (default: False), Tensors will have the original data types of the DataFrame columns.
    - If False, Tensors will be cast to float type.

    Returns:
    A tuple of Tensors, one for each input DataFrame.
    """
    # Create a tensor from dataframe (convert inputs to float)
    return (np.array(df)for df in args) if target else (np.array(df).astype(float) for df in args)

## ***Data preparation***

**We will use a base table of 100 features selected from a set of features generated with Deep Feature Synthesis on the Home Credit - Credit Risk Model Stability competition dataset totaling over 1,500,000 examples.**

In [3]:
dataset = pd.read_parquet("/kaggle/input/deep-feature-synthesis-home-credit-stability/base_100features.parquet")
dataset

,WEEK_NUM,COUNT(person_1),MODE(person_1.contaddr_district_15M),MODE(person_1.contaddr_zipcode_807M),MODE(person_1.education_927M),MODE(person_1.empladdr_district_926M),MODE(person_1.empladdr_zipcode_114M),MODE(person_1.incometype_1044T),MODE(person_1.language1_981M),MODE(person_1.role_1084L),...,MODE(static_cb_0.education_88M),MODE(static_cb_0.maritalst_385M),MODE(static_cb_0.requesttype_4525192L),SUM(static_cb_0.days120_123L),SUM(static_cb_0.days30_165L),MAX_MIN_DELTA(applprev_2.num_group2),MONTH(date_decision),SEASON(date_decision),WEEKDAY(date_decision),target
case_id,,,,,,,,,,,,,,,,,,,,,
0,0,4,259,2828,5,221,2093,6,2,2,...,2,2,0,0.0,0.0,0.0,1,3,3,0
1,0,5,259,2828,5,221,2093,6,2,0,...,2,2,0,0.0,0.0,0.0,1,3,3,0
2,0,5,259,2828,5,221,2093,8,2,0,...,2,2,0,0.0,0.0,1.0,1,3,4,0
3,0,3,259,2828,5,221,2093,8,2,0,...,2,2,0,0.0,0.0,2.0,1,3,3,0
4,0,4,259,2828,5,221,2093,8,2,2,...,2,2,0,0.0,0.0,1.0,1,3,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2703450,91,1,143,356,5,221,2093,0,1,0,...,4,3,0,0.0,0.0,2.0,10,0,0,0
2703451,91,2,403,2825,5,221,2093,0,1,0,...,4,3,0,0.0,0.0,3.0,10,0,0,0
2703452,91,1,273,3202,5,221,2093,1,1,0,...,4,3,0,2.0,0.0,1.0,10,0,0,0
2703453,91,2,148,1959,5,221,2093,0,1,0,...,4,0,0,2.0,1.0,3.0,10,0,0,0
2703454,91,1,42,251,5,221,2093,0,0,0,...,4,5,0,1.0,0.0,3.0,10,0,0,0

In [4]:
# You can notice that the positive class is extremely under represented (totalling about 3% of the entire dataset)
# This complicates the training process as the model will likely get a 97% classification accuracy by always prediction class 0
# So we have to find a solution to that problem first
dataset[dataset["target"] == 1]

,WEEK_NUM,COUNT(person_1),MODE(person_1.contaddr_district_15M),MODE(person_1.contaddr_zipcode_807M),MODE(person_1.education_927M),MODE(person_1.empladdr_district_926M),MODE(person_1.empladdr_zipcode_114M),MODE(person_1.incometype_1044T),MODE(person_1.language1_981M),MODE(person_1.role_1084L),...,MODE(static_cb_0.education_88M),MODE(static_cb_0.maritalst_385M),MODE(static_cb_0.requesttype_4525192L),SUM(static_cb_0.days120_123L),SUM(static_cb_0.days30_165L),MAX_MIN_DELTA(applprev_2.num_group2),MONTH(date_decision),SEASON(date_decision),WEEKDAY(date_decision),target
case_id,,,,,,,,,,,,,,,,,,,,,
4,0,4,259,2828,5,221,2093,8,2,2,...,2,2,0,0.0,0.0,1.0,1,3,4,1
101,0,4,259,2828,5,221,2093,1,2,2,...,2,2,0,0.0,0.0,1.0,1,3,3,1
118,0,4,259,2828,5,221,2093,1,2,2,...,2,2,0,0.0,0.0,0.0,1,3,3,1
129,0,4,259,2828,5,221,2093,8,2,2,...,2,2,0,0.0,0.0,0.0,1,3,4,1
148,0,4,259,2828,5,221,2093,1,2,2,...,2,2,0,0.0,0.0,0.0,1,3,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2702884,91,1,515,2177,5,221,2093,6,0,0,...,4,4,0,0.0,0.0,1.0,10,0,4,1
2702904,91,1,297,1304,5,221,2093,8,1,0,...,4,0,0,1.0,1.0,2.0,10,0,4,1
2703005,91,1,232,233,5,221,2093,6,0,0,...,4,0,0,3.0,3.0,2.0,10,0,5,1
2703400,91,1,798,1536,5,221,2093,8,1,0,...,4,0,0,8.0,4.0,2.0,10,0,0,1
2703411,91,1,511,1850,5,221,2093,6,1,0,...,4,0,0,2.0,0.0,5.0,10,0,0,1

In [5]:
# Drop WEEK_NUM and target to form the training entries X
week_num = dataset["WEEK_NUM"]
target = dataset["target"]
dataset.drop(columns=["WEEK_NUM", "target"], inplace=True)
dataset

,COUNT(person_1),MODE(person_1.contaddr_district_15M),MODE(person_1.contaddr_zipcode_807M),MODE(person_1.education_927M),MODE(person_1.empladdr_district_926M),MODE(person_1.empladdr_zipcode_114M),MODE(person_1.incometype_1044T),MODE(person_1.language1_981M),MODE(person_1.role_1084L),MODE(person_1.sex_738L),...,MODE(static_cb_0.education_1103M),MODE(static_cb_0.education_88M),MODE(static_cb_0.maritalst_385M),MODE(static_cb_0.requesttype_4525192L),SUM(static_cb_0.days120_123L),SUM(static_cb_0.days30_165L),MAX_MIN_DELTA(applprev_2.num_group2),MONTH(date_decision),SEASON(date_decision),WEEKDAY(date_decision)
case_id,,,,,,,,,,,,,,,,,,,,,
0,4,259,2828,5,221,2093,6,2,2,0,...,3,2,2,0,0.0,0.0,0.0,1,3,3
1,5,259,2828,5,221,2093,6,2,0,1,...,3,2,2,0,0.0,0.0,0.0,1,3,3
2,5,259,2828,5,221,2093,8,2,0,0,...,3,2,2,0,0.0,0.0,1.0,1,3,4
3,3,259,2828,5,221,2093,8,2,0,0,...,3,2,2,0,0.0,0.0,2.0,1,3,3
4,4,259,2828,5,221,2093,8,2,2,0,...,3,2,2,0,0.0,0.0,1.0,1,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2703450,1,143,356,5,221,2093,0,1,0,0,...,4,4,3,0,0.0,0.0,2.0,10,0,0
2703451,2,403,2825,5,221,2093,0,1,0,0,...,4,4,3,0,0.0,0.0,3.0,10,0,0
2703452,1,273,3202,5,221,2093,1,1,0,1,...,4,4,3,0,2.0,0.0,1.0,10,0,0
2703453,2,148,1959,5,221,2093,0,1,0,0,...,1,4,0,0,2.0,1.0,3.0,10,0,0
2703454,1,42,251,5,221,2093,0,0,0,0,...,4,4,5,0,1.0,0.0,3.0,10,0,0

In [6]:
# Split the dataset into training and test sets (randomly shuffling the data)
# Only 5% of the data will be used as the test set (the dataset being really big, 5% should be largely enough)
X_train, X_test, Y_train, Y_test = train_test_split(dataset, target, test_size=0.05, shuffle=True, random_state=123)

In [7]:
# keep the true test labels in a Dataframe before converting to tensor
true_label_test = pd.DataFrame(Y_test)
true_label_test

         target
case_id
1017805       0
2543910       0
225134        0
955887        0
23690         0
...         ...
2540270       0
2553269       0
947602        0
755641        0
1663420       0

[76333 rows x 1 columns]

In [8]:
# Convert Xs and Ys to tensor (np.ndarray)
X_train, X_test = convert_to_tensor(X_train, X_test)
Y_train, Y_test = convert_to_tensor(Y_train, Y_test, target=True)

In [9]:
X_train.shape, X_test.shape

((1450326, 100), (76333, 100))

In [10]:
Y_train.dtype, X_train.dtype

(dtype('int64'), dtype('float64'))

## ***StandardScaler for normalization***

**This estimator will act as a preprocessing layer that shifts and scale inputs into a distribution centered around 0 with standard deviation 1. It computes mean and variance when .fit is called and transforms the input as follow: input = (input - mean) / sqrt(var) when .transform is called.**

In [11]:
normalizer = StandardScaler()
normalizer.fit(X_train)
normalizer.transform(X_test[:1])

array([[ 0.04624721, -0.28207035, -1.98300306, -4.6552798 ,  0.24187498,
         0.19741905,  0.78313462,  1.19394783, -0.37999895, -0.77626192,
        -1.37151   , -0.24940889, -2.18956401,  0.65681083, -1.01999347,
        -0.92357804, -1.00080705,  0.49003232, -1.18272814,  0.65047138,
         0.52157697, -0.02339314, -0.68215513, -0.16142495, -0.99749769,
        -0.70858183,  0.12254756,  0.11174086, -0.62869268,  0.75663826,
        -0.53296634, -1.04587252, -0.71103933, -0.11861729, -0.02432021,
        -0.88033272, -0.38889713, -2.00131617, -0.47380036, -1.32754398,
        -1.39047098, -1.5428801 , -0.87488219, -0.9901183 , -0.85514003,
        -1.60920835, -1.28708186, -1.05573749, -0.81731618, -1.3617547 ,
        -0.79203177, -1.00521888, -0.14500467,  0.01480454,  0.42456864,
        -0.78026421, -0.57582792,  0.37803943, -0.74890573, -0.62719456,
        -1.02840467, -0.9170443 , -0.64738589, -0.5287307 , -0.40075795,
        -0.68189228, -0.66453196, -0.51602374, -0.34319528, -0.29621254,
        -0.61305319, -0.60624445,  0.55362101, -0.63051401, -0.09753332,
        -0.58637338, -0.36787165, -0.07309856, -0.62503323, -0.74385366,
        -0.89408481,  1.04698556, -0.60115759, -0.07322425, -0.07697114,
        -0.26548732, -0.45430307, -1.57829635, -0.77481505, -2.64558136,
         0.83276999,  0.15779554,  0.55023116, -0.8052502 , -0.71587263,
        -0.54031029, -1.39263587,  0.73263586,  0.31888226, -0.49515056]])

## ***Dealing with imbalance***

As we observed earlier, the dataset is highly unbalanced, requiring a strategy for the model to effectively learn to distinguish between the two classes. Without such a strategy, the model is likely to predict class 0 for almost every example and still achieve a high classification accuracy. Therefore, accuracy is not as relevant for this kind of dataset. To evaluate the model, we need metrics that can assess its ability to **recognize the minority class**. By weighting the classes, we penalize the model more heavily for misclassifying the minority class than the majority class.

Additionally, we will use precision and recall to evaluate the model's performance. Both metrics provide insights into the model's ability to accurately predict the positive class. Precision measures the percentage of true positive predictions among all examples predicted as positive, while recall measures the percentage of actual positive cases that the model correctly identified as positive.

In [12]:
# Compute class weights 
# Run if not dataset resampled (to train on the whole training set)
class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(Y_train), y=Y_train)
class_weights = {0: class_weights[0], 1: class_weights[1]/1.5}
class_weights

{0: 0.5162114467827323, 1: 10.614134849715677}

## ***Make pipeline***

In [13]:
pipe = make_pipeline(StandardScaler(),
                     RandomForestClassifier(n_estimators=200, criterion='gini', max_features="sqrt", bootstrap=True, 
                                            class_weight=class_weights, n_jobs=-1, warm_start=False, random_state=123, max_samples=None))

In [14]:
pipe.fit(X=X_train, y=Y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('randomforestclassifier',
                 RandomForestClassifier(class_weight={0: 0.5162114467827323,
                                                      1: 10.614134849715677},
                                        n_estimators=200, n_jobs=-1,
                                        random_state=123))])

In [15]:
pipe.score(X=X_test, y=Y_test)

0.9679168904667707

In [16]:
y_pred = pipe.predict(X=X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [17]:
y_pred_probs = pipe.predict_proba(X=X_test)
y_pred_probs

array([[1.   , 0.   ],
       [1.   , 0.   ],
       [0.985, 0.015],
       ...,
       [0.975, 0.025],
       [0.995, 0.005],
       [0.98 , 0.02 ]])

In [18]:
# Chaniging classification threshold
y_pred = (y_pred_probs[:, 1] >= 0.055).astype(int)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [19]:
recall_score(Y_test, y_pred)

0.6097261953412342

In [20]:
precision_score(Y_test, y_pred)

0.1037985251147906

In [21]:
roc_auc_score(Y_test, y_pred_probs[:, 1])

0.80397697571871

In [22]:
accuracy_score(Y_test, y_pred)

0.8187284660631706

## ***Conclusion***